[project]
name = "neendai"
version = "1.0.0"
description = "Sleep Apnea Detection System"
requires-python = ">=3.11"
dependencies = []

[project.scripts]
app = "app:app"

[tool.setuptools]
packages = ["src"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

